import Head from "next/head";
import styles from "styles/index.module.scss";

export default function Home() {
  return (
    <div className={styles.divMainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      123
    </div>
  )
}
